### ISSUE TITLE
SCAM!!!

### ISSUE THREAD

**Issue by pumpfunbotsourcecode** [milkerman14/pump.fun-sniper-bot#1]
This is a scam, beware!

**Comment by milkerman14** [comment]
Okay, you're advertising your own garbage lol. PM for video proof or live demo :)

**Comment by pumpfunbotsourcecode** [comment]
Milkermans code is a wallet drainer hidden in the obfuscated code. Several people have reported to us that their wallets have been drained using his code. DO NOT BUY IT OR YOU WILL LOSE YOUR SOL.  Our sources report that he sells you the code and then blocks you. He goes by discord names 'Crypto King', 'Milkman', 'Murky'.
