### ISSUE TITLE
THIS IS A WALLET DRAINER SCAM

### ISSUE THREAD

**Issue by pumpfunbotsourcecode** [milkerman14/pump.fun-sniper-bot#2]
Milkermans code is a wallet drainer hidden in the obfuscated code. Several people have reported to us that their wallets have been drained using his code. DO NOT BUY IT OR YOU WILL LOSE YOUR SOL. Our sources report that he sells you the code and then blocks you. He goes by discord names 'Crypto King', 'Milkman', 'Murky'. He will send you a screenshot of his UI showing some code but will send you a 135MB version of obfusicated code that will drain your wallet.

**Comment by milkerman14** [comment]
code comes unobfuscated lol
